### ISSUE TITLE
Allow use of expandEnv flag for spire configuration

### ISSUE THREAD

**Issue by joshuastern** [spiffe/tornjak#109]
We are using the expandEnv flag when running the Spire server in order to expand environment variables in the configuration file. Right now the expandEnv flag is being hardcoded as false within tornjak. We would like to be able to use this flag when running tornjak.

**Comment by maia-iyer** [comment]
Hello, thank you for making this issue and suggestion! We will begin working on this and have an update soon!

**Comment by maia-iyer** [comment]
So we have added the ability to expand env of the Tornjak config. However, the Tornjak container is now separate from the SPIRE server container. So this means the environment variables will not be the same, and expandEnv of the SPIRE config will be problematic. 

The SPIRE server config does not affect any execution of Tornjak except for the command to print the config. We are planning on replacing this function as well with something that directly calls the SPIRE server. 

Are there any other specific concerns that should be addressed?

**Comment by maia-iyer** [comment]
Closing this issue for now. If there are other concerns, please reach out and open another issue or follow up!
