### ISSUE TITLE
Tornjak failes with a 400 error on api/agent/list in my webbrowser

### ISSUE THREAD

**Issue by marcofranssen** [spiffe/tornjak#210]
When navigating to the agent list in Tornjak frontend it returns a 400 error response on the following api endpoint.

http://localhost:10000/api/agent/list

In the details of the error it shows the following.

```
failed to list agents: datastore-sql: disk I/O error
```

Based on the error details I think the error code should be a `500` http response.

To get rid of the error I removed the persistent volume claim and redeployed spire-server and tornjak. See https://github.com/spiffe/helm-charts example on how it is deployed.

**Comment by maia-iyer** [comment]
Hello, thank you for your feedback! This is good point for an open PR #127 currently on expanding and changing the error handling in the frontend - we'll take this into account :) 

When you removed the error, what do you mean by removing the persistent volume claim? When deploying, were you using a previous version of the helm charts or one of our tutorial deployment files?

**Comment by mrsabath** [comment]
@maia-iyer when Tornjak backend is deployed it takes in account a storage that already exists and that was created during Spire server deployment. Typically this storage is done through Persistent Volume Claims (PVC).
