### ISSUE TITLE
Add support for arm64

### ISSUE THREAD

**Issue by marcofranssen** [spiffe/tornjak#219]
To support deployment to arm64 cluster nodes using the helm-charts in multi architecture clusters it would be great if tornjak also has an arm64 build.

See this PR how I contributed this to spire:

https://github.com/spiffe/spire/pull/3607

Currently I'm working around deployment issues by using a nodeSelector to force Spire back to amd64 nodes for all the tornjak involved components.

```bash
nodeSelector:
  kubernetes.io/arch: amd64
```

**Comment by mrsabath** [comment]
See this https://github.com/spiffe/spire/pull/3607 and https://github.com/spiffe/spire/issues/1984 as a reference

**Comment by maia-iyer** [comment]
closed by #358 and #347
