### ISSUE TITLE
Rename directory in Tornjak Backend container

### ISSUE THREAD

**Issue by mrsabath** [spiffe/tornjak#259]
Since we are running tornjak in a separate container than SPIRE, we should probably rename the current directory from `/opt/spire` to `/opt/tornjak`

**Comment by vjesu5** [comment]
Hi! Work is in progress for the opened issue: #463.
It's still in Draft until I regularize the DCO check (_it is one of my first contributions_).

**Comment by vjesu5** [comment]
PR #463 is available for review.
