### ISSUE TITLE
Backend: Enable two ports for HTTP and HTTPS

### ISSUE THREAD

**Issue by mrsabath** [spiffe/tornjak#268]
We should enable two ports: 
* HTTP e.g. 10080
* HTTPS e.g. 10443

When Tornjak is running HTTP connection and user connects on HTTPS port,  the client should receive an error code such as "SSL/TLS handshake failure" or "unable to establish secure connection." 

When Tornjak is running with TLS or mTLS connection enabled, and user connects to HTTP port, they should get a permanent redirect to HTTPS port. 

Suggested configuration:

```
server {
  spire_socket_path = "unix:///tmp/spire-server/private/api.sock"

  http {
    port = 10080 # container port for insecure connection
  }
  https {
    port     = 10443 # container port for secure connection
    cert     = …
    key      = …
    clientCA = … # (optional setting required for mTLS)
  }
}

plugins { ...
```

When optional values provided, but not set correctly, Tornjak throws an error message and exits. 
When connection successfully started, Tornjak console logs a status message.

**Comment by marcofranssen** [comment]
Basically we need an implementation like this.

https://marcofranssen.nl/build-a-go-webserver-on-http-2-using-letsencrypt#tldr

**Comment by marcofranssen** [comment]
Took a stab at it https://github.com/spiffe/tornjak/pull/282

**Comment by mrsabath** [comment]
The image crashes, needs fixing
