### ISSUE TITLE
Search function does not work on Entries 

### ISSUE THREAD

**Issue by mrsabath** [spiffe/tornjak#303]
Looks to me that once we introduced the pagination, only the first page is used for searching the records. If the searched record is not present on the first page (first set) it is not used for producing the results.

Example, before search:
![image](https://github.com/spiffe/tornjak/assets/6954688/60d76414-111e-4be6-8d13-8b8ad8d397c7)
 Example after typing search on page 2. 
 
![image](https://github.com/spiffe/tornjak/assets/6954688/a3ba8767-2885-4ec9-a57e-437e0bd6cfb3)

**Comment by mamy-CS** [comment]
This was tested and verified that it works, @mrsabath any issues with this after our last test?
