### ISSUE TITLE
User Management helm extension (Keycloak)

### ISSUE THREAD

**Issue by mamy-CS** [spiffe/tornjak#344]
Add configuration to Tornjak Helm to be able to start keycloak user management by turning on a flag.

**Comment by mamy-CS** [comment]
Blocker https://github.com/spiffe/tornjak/issues/343

**Comment by mamy-CS** [comment]
Blocker #343 has been solved - https://github.com/spiffe/helm-charts-hardened/pull/259/commits/44a9c2903a974fa8f94a91cd9185c9692513672c

**Comment by mamy-CS** [comment]
Simplify tornjak realm import using keycloak-config cli

**Comment by mamy-CS** [comment]
realm import simplification added

**Comment by mamy-CS** [comment]
keycloak-config-cli currently works only on image docker.io/bitnami/keycloak-config-cli:5.10.0-debian-12-r9
submitted an issue to keycloak

**Comment by maia-iyer** [comment]
completed by [helm #259](https://github.com/spiffe/helm-charts-hardened/pull/259)
